// Static SEO of the site files (spec §5.4, A-06): SEO-01 robots.txt, SEO-05 sitemap.
// Sources: the robots.txt of the project (root, public/ or static/) and, with --url, the
// one served by the development URL. Each source gives its own findings.
import fs from 'node:fs';
import path from 'node:path';
import { pass, fail, unverified } from './api.mjs';
import { parseRobots, isAllowed } from '../robots.mjs';
import { checkSitemap } from '../xml-check.mjs';
import { findSiteFile, generatedBy } from '../site-files.mjs';
import { seoGate, seoPages, indexable, staticAttr } from './seo-common.mjs';

const MAX_SITEMAP_BYTES = 10 * 1024 * 1024;

// One source per robots.txt: { file, origin, text } when there is a text to read, else
// { file, origin, none } (none = why it cannot be read, or null for "absent: everything allowed").
// With --url the served robots.txt is the truth: a project without the file adds nothing.
function robotsSources(pctx) {
  const out = [];
  const rel = findSiteFile(pctx.project, 'robots.txt');
  const gen = rel ? null : generatedBy(pctx.project, 'robots');
  if (rel) out.push({ file: rel, origin: 'file', text: fs.readFileSync(path.join(pctx.project, ...rel.split('/')), 'utf8') });
  else if (gen) out.push({ file: gen, origin: 'file', none: `robots.txt is generated by ${gen}` });
  else if (!pctx.site) out.push({ file: 'robots.txt', origin: 'file', none: null });
  const r = pctx.site?.robots;
  if (r) {
    if (r.error) out.push({ file: r.url, origin: 'url', none: r.error });
    else if (r.status === 404) out.push({ file: r.url, origin: 'url', none: null });
    else if (r.status !== 200) out.push({ file: r.url, origin: 'url', none: `HTTP ${r.status}` });
    else out.push({ file: r.url, origin: 'url', text: r.text });
  }
  return out;
}

// Same-origin paths of the stylesheets and scripts the checked pages load.
function renderAssets(pctx) {
  const paths = new Set();
  for (const page of seoPages(pctx)) {
    if (page.skip) continue;
    for (const el of page.markup.elements) {
      if (el.component) continue;
      let ref = null;
      if (el.tag === 'script') ref = staticAttr(el, 'src');
      else if (el.tag === 'link' && (staticAttr(el, 'rel') ?? '').toLowerCase().split(/\s+/).includes('stylesheet')) ref = staticAttr(el, 'href');
      if (ref && ref.startsWith('/') && !ref.startsWith('//')) paths.add(ref.split(/[?#]/)[0]);
    }
  }
  return [...paths].sort();
}

function publicRoutes(pctx) {
  const routes = new Set(['/']);
  for (const p of pctx.site?.pages ?? []) if (!p.error) routes.add(p.path);
  return [...routes].sort();
}

function seo01(pctx) {
  const gate = seoGate(pctx);
  if (gate) return gate;
  const out = [];
  for (const src of robotsSources(pctx)) {
    const where = { file: src.file };
    if (src.text === undefined) {
      if (src.none) out.push(unverified(src.none, where));
      else out.push(pass('no robots.txt', { ...where, reason: 'no robots.txt: everything is allowed' }));
      continue;
    }
    if (!indexable(pctx)) { out.push(pass('not indexable', { ...where, reason: 'web.indexable is false: blocking crawlers is declared' })); continue; }
    const robots = parseRobots(src.text);
    const found = [];
    for (const route of publicRoutes(pctx)) {
      const r = isAllowed(robots, route);
      if (!r.allowed) found.push(fail(`blocks ${route}`, { ...where, line: r.rule.line, reason: `robots.txt blocks the public route ${route} (${r.rule.pattern})` }));
    }
    for (const asset of renderAssets(pctx)) {
      const r = isAllowed(robots, asset);
      if (!r.allowed) found.push(fail(`blocks ${asset}`, { ...where, line: r.rule.line, reason: `robots.txt blocks the render asset ${asset} (${r.rule.pattern})` }));
    }
    if (!robots.sitemaps.length) found.push(fail('no sitemap', { ...where, reason: 'robots.txt references no sitemap' }));
    out.push(...(found.length ? found : [pass('robots', where)]));
  }
  return out;
}

function sitemapPath(declared) {
  try { return new URL(declared, 'http://x.invalid').pathname; } catch { return null; }
}

function seo05(pctx) {
  const gate = seoGate(pctx);
  if (gate) return gate;
  const out = [];
  for (const src of robotsSources(pctx)) {
    if (src.text === undefined) continue;
    const declared = parseRobots(src.text).sitemaps;
    if (!declared.length) { out.push(unverified('no sitemap referenced (see SEO-01)', { file: src.file })); continue; }
    for (const s of declared) {
      const p = sitemapPath(s.url);
      if (!p) { out.push(fail(`sitemap ${s.url}`, { file: src.file, line: s.line, reason: `invalid sitemap URL ${s.url}` })); continue; }
      if (src.origin === 'url') {
        const got = (pctx.site.sitemaps ?? []).find((x) => x.declared === s.url);
        if (!got) out.push(unverified(`sitemap ${p} not fetched`, { file: src.file }));
        else if (got.error) out.push(unverified(got.error, { file: got.url }));
        else if (got.status === 404) out.push(fail(`sitemap ${p} missing`, { file: got.url, reason: `sitemap ${p} referenced by robots.txt answers 404` }));
        else if (got.status !== 200) out.push(unverified(`HTTP ${got.status}`, { file: got.url }));
        else out.push(verdict(checkSitemap(got.text), got.url, p));
        continue;
      }
      const rel = findSiteFile(pctx.project, p);
      if (!rel) {
        const gen = generatedBy(pctx.project, 'sitemap');
        out.push(gen ? unverified(`sitemap is generated by ${gen}`, { file: gen })
          : fail(`sitemap ${p} missing`, { file: src.file, line: s.line, reason: `sitemap ${p} referenced by robots.txt is not in the project` }));
        continue;
      }
      const abs = path.join(pctx.project, ...rel.split('/'));
      if (fs.statSync(abs).size > MAX_SITEMAP_BYTES) { out.push(unverified('sitemap larger than 10 MB', { file: rel })); continue; }
      out.push(verdict(checkSitemap(fs.readFileSync(abs, 'utf8')), rel, p));
    }
  }
  if (!out.length) out.push(unverified('no robots.txt, so no sitemap is referenced', {}));
  return out;
}

function verdict(res, file, p) {
  return res.ok
    ? pass(`sitemap ${p}`, { file, measure: { kind: res.kind, count: res.count } })
    : fail(`sitemap ${p} invalid`, { file, line: res.line, reason: `sitemap ${p} is not valid: ${res.error}` });
}

export const RULES = [
  { id: 'SEO-01', checkProject: seo01 },
  { id: 'SEO-05', checkProject: seo05 },
];
